export const initialCards = [
    {content: '🍎', isCorrect: false, revealed: false},
    {content: '🍎', isCorrect: false, revealed: false},
    {content: '🍌', isCorrect: false, revealed: false},
    {content: '🍌', isCorrect: false, revealed: false},
    {content: '🍇', isCorrect: false, revealed: false},
    {content: '🍇', isCorrect: false, revealed: false},
    {content: '🍉', isCorrect: false, revealed: false},
    {content: '🍉', isCorrect: false, revealed: false},
    {content: '🐶', isCorrect: false, revealed: false},
    {content: '🐶', isCorrect: false, revealed: false},
    {content: '🐱', isCorrect: false, revealed: false},
    {content: '🐱', isCorrect: false, revealed: false},
    {content: '🚗', isCorrect: false, revealed: false},
    {content: '🚗', isCorrect: false, revealed: false},
    {content: '✈️', isCorrect: false, revealed: false},
    {content: '✈️', isCorrect: false, revealed: false},
]